# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
# #     upload_to_testflight
#   end
# end
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :sync_all_development do
#     sync_device_info
    match(type: "development",
    git_basic_authorization: Base64.strict_encode64("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")

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  end
  lane :sync_device_info do
    register_devices(devices_file: "fastlane/devices.txt")
  end
end